----
 - name: Copy firewall rules to /etc/sysconfig
   copy: src=iptables_rules.txt dest=/etc/sysconfig/iptables
   sudo: yes

 - name: Delete tmp files from /tmp
   file: path=/tmp/iptables_rules.txt state=absent
