---

- debug: msg="RAILS_ENV={{rails_env}}"

- name: Check if database exists
  command: /usr/bin/psql -d {{ rails_env }} -U postgres -c "\\d"
  register: command_result
  ignore_errors: True

- name: Rake create
  command:
    /usr/local/bin/rake db:create RAILS_ENV="{{rails_env}}"
    chdir={{ app_path }}/{{ deploy_server_role }}
  when: "'FATAL:  database \"production\" does not exist' in command_result.stderr"

- name: Rake migrate
  command:
    /usr/local/bin/rake db:migrate RAILS_ENV="{{rails_env}}"
    chdir={{ app_path }}/{{ deploy_server_role }}

- name: Start rails
  command:
    rails server thin -d -e "{{rails_env}}" -p "{{port}}"
    chdir={{ app_path }}/{{ deploy_server_role }}
