---
- hosts: all
  vars:
    http_port: 80
    max_clients: 200
    remote_user: deploy
  tasks:

  - include: disable_selinux.yml

  - name: Install ntp
    yum: pkg=ntp state=present
    sudo: yes

  - name: Copying ntp.conf to /etc
    copy: src=ntp.conf dest=/etc/ntp.conf mode=755
    sudo: yes

  - name: Adjust timezone
    command: ln -s -f /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
    sudo: yes

  - name: Starting ntp service and set it to boot
    service: name=ntpd state=restarted enabled=yes
    sudo: yes

  - name: The time was set to
    command: date
    register: date_output

  - debug: msg="Date was set to {{ date_output.stdout }}"
